### ISSUE TITLE
1.2.0 breaks url(#divId)

### ISSUE THREAD

**Issue by Alphadelta14** [webpack/loader-utils#133]
Ran into an issue where fresh upgrade to 1.2.0 started breaking webpack builds of less where we were using an svg fill snippet like
```
svg.sample {
    rect {
        fill: url(#gradient);
    }
}
```

The error showed up like
```
    ERROR in ./frontend/chart-setup.less (./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./frontend/chart-setup.less)
    Module not found: Error: Can't resolve './' in '/home/ubuntu/workspace/proj/frontend'
     @ ./frontend/chart-setup.less (./node_modules/css-loader??ref--6-1!./node_modules/less-loader/dist/cjs.js??ref--6-2!./frontend/chart-setup.less) 7:12630-12643
```

Pinning to 1.1.0 fixed this issue.

My initial guess is that it is trying to load ./index#gradient as an image or something.

**Comment by yibn2008** [comment]
+1, a lot of apps broke in my company due to this upgrade, please fixed it

**Comment by vladimiry** [comment]
Also such error
```
ERROR in ./src/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleNotFoundError: Module not found: Error: Can't resolve './pages/' in '/dev/protonmail/WebClient/src/sass'
    at factory.create (/dev/protonmail/WebClient/node_modules/webpack/lib/Compilation.js:821:10)
    at factory (/dev/protonmail/WebClient/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/dev/protonmail/WebClient/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/dev/protonmail/WebClient/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
```
See details here https://github.com/ProtonMail/WebClient/issues/130

**Comment by youluna** [comment]
We use it as follows:
```css
@font-face {
    src: url("//at.alicdn.com/t/font_515771_emcns5054x3whfr.eot");
}
```


https://travis-ci.com/alibaba-fusion/next/builds/95698744#L876

**Comment by evilebottnawi** [comment]
Regressions, will be fixed in near future

**Comment by evilebottnawi** [comment]
WIP

**Comment by evilebottnawi** [comment]
@youluna can't reproducible you problem, we always ignore all what starts with `//` (in previous and in this version)

**Comment by huston007** [comment]
Also affected `html-loader` so we've got errors like that `Module not found: Error: Can't resolve './{{icon}}' in '../node_modules/@jetbrains/ring-ui/components/error-message-ng'`

**Comment by evilebottnawi** [comment]
@hulkish @huston007 yep, this fix it problem, update your deps and feel free to feedback
